import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Portfolio Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div className="p-2 grid grid-cols-2 gap-2 md:grid-cols-4 md:p-4">
        <h2 className="text-xl font-semibold text-slate-700 md:col-start-4 md:row-start-2 md:flex"><span className="self-center mr-4">
        Welcome, Hello World</span>
        <button className="p-4 bg-slate-200" onClick={() => router.push('/login')}>LOGIN</button>
   
        </h2>
        <div className='text-lg font-bold text-gray-600 md:col-start-2 md:row-start-2 md:flex'><span className='self-end'>
        @inas.istiqlaliyyah</span></div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3]  md:col-start-3 overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>

        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] md:col-start-2 overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] md:col-start-4 overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] md:col-start-3 overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
        <div className="bg-blue-500 aspect-[4/3] rounded-lg md:aspect-[3/4] xl:aspect-[4/3] md:col-start-3 overflow-hidden group relative hover:scale-95 duration-500 transition-all">
          <div className="bg-[url('https://picsum.photos/536/354')] w-full h-full bg-cover bg-center absolute group-hover:scale-125 transition-all duration-500 group-hover:rotate-12">
          </div>
        </div>
      </div>
    

      <footer className="container flex justify-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
